export const customReportsColumns = [
  {name: 'BY_DAILY', header: "날짜별", width: 100, textAlign: 'center'},
  {name: 'BY_WEEKLY', header: "주별", width: 100, textAlign: 'center'},
  {name: 'BY_MONTHLY', header: "월별", width: 100, textAlign: 'center'},
  {name: 'BY_ADVERTISE', header: "광고주 명", width: 100, textAlign: 'center'},
  {name: 'BY_CAMPAIGN', header: "캠페인 명", width: 100, textAlign: 'center'},
  {name: 'BY_PRODUCT', header: "광고 상품", width: 100, textAlign: 'center'},
  {name: 'BY_EVENT', header: "이벤트 명", width: 100, textAlign: 'center'},
  {name: 'COUNT_BY_ADVERTISE', header: "광고주 수", width: 100, textAlign: 'center'},
  {name: 'TOTAL_EXPOSURE_COUNT', header: "총 노출수", width: 100, textAlign: 'center'},
  {name: 'EXPOSURE_COUNT', header: "노출수", width: 100, textAlign: 'center'},
  {name: 'CLICK_COUNT', header: "총 클릭수", width: 100, textAlign: 'center'},
  {name: 'VALID_CLICK_COUNT', header: "클릭수", width: 100, textAlign: 'center'},
  {name: 'CLICK_RATE', header: "클릭율", width: 100, textAlign: 'center'},
  {name: 'COST_AMOUNT', header: "비용", width: 100, textAlign: 'center'},
  {name: 'CPC', header: "CPC", width: 100, textAlign: 'center'},
  {name: 'CONVERSION_COUNT', header: "전환수", width: 100, textAlign: 'center'},
  {name: 'CONVERSION_RATE', header: "전환율", width: 100, textAlign: 'center'},
  {name: 'CONVERSION_PRICE', header: "전환비용", width: 100, textAlign: 'center'},
  {name: 'AMOUNT_PURCHASED_AVG', header: "평균", width: 100, textAlign: 'center'},
  {name: 'SESSION_CONVERSION_AMOUNT', header: "세션 매출", width: 100, textAlign: 'center'},
  {name: 'SESSION_CONVERSION_ROAS', header: "세션 ROAS", width: 100, textAlign: 'center'},
  {name: 'DIRECT_CONVERSION_AMOUNT', header: "직접 매출", width: 100, textAlign: 'center'},
  {name: 'DIRECT_CONVERSION_ROAS', header: "직접 ROAS", width: 100, textAlign: 'center'},
  {name: 'ROAS', header: "ROAS", width: 100, textAlign: 'center'},
  {name: 'EXPOSURE_CONVERSION_AMOUNT', header: "노출 매출", width: 100, textAlign: 'center'},
  {name: 'EXPOSURE_CONVERSION_ROAS', header: "노출 ROAS", width: 100, textAlign: 'center'},
  {name: 'E_CPM', header: "eCPM", width: 100, textAlign: 'center'},
]
