export const database = [
  {
    id: 0,
    size: 'IMG200_200',
    title: '',
    titleSize: 12,
    titleColor: '',
    titleBold: false,
    titleItalic: false,
    titleUnderline: false,
    titleFamily: '',
    mainImage: '',
    backgroundImage: '',
    backgroundColor: '',
    buttonTitle: '',
    buttonColor: '',
    buttonBackgroundColor: '',
  },
  {
    id: 1,
    size: 'IMG300_200',
    title: '',
    titleSize: 12,
    titleColor: '',
    titleBold: false,
    titleItalic: false,
    titleUnderline: false,
    titleFamily: '',
    mainImage: '',
    backgroundImage: '',
    backgroundColor: '',
    buttonTitle: '',
    buttonColor: '',
    buttonBackgroundColor: '',
  },
  {
    id: 2,
    size: 'IMG500_500',
    title: '',
    titleSize: 12,
    titleColor: '',
    titleBold: false,
    titleItalic: false,
    titleUnderline: false,
    titleFamily: '',
    mainImage: '',
    backgroundImage: '',
    backgroundColor: '',
    buttonTitle: '',
    buttonColor: '',
    buttonBackgroundColor: '',
  },
]

export const fontTypes = [
  {key: 0, value: 'Dotum', label: '돋움'},
  {key: 1, value: 'Gulim', label: '굴림'},
  {key: 2, value: 'Malgun Gothic', label: '맑은고딕'},
  {key: 3, value: 'Batang', label: '바탕'},
  {key: 4, value: 'New Gulim', label: '새굴림'},
  {key: 5, value: '궁서체', label: '궁서체'}
]