export const database = [
  {
    id: 0,
    size: 'IMG200_200',
    title: '',
    titleSize: 12,
    titleColor: '',
    titleBold: false,
    titleItalic: false,
    titleUnderline: false,
    titleFamily: '',
    mainImage: '',
    backgroundImage: '',
    backgroundColor: '',
    buttonTitle: '',
    buttonColor: '',
    buttonBackgroundColor: '',
  },
  {
    id: 1,
    size: 'IMG300_200',
    title: '',
    titleSize: 12,
    titleColor: '',
    titleBold: false,
    titleItalic: false,
    titleUnderline: false,
    titleFamily: '',
    mainImage: '',
    backgroundImage: '',
    backgroundColor: '',
    buttonTitle: '',
    buttonColor: '',
    buttonBackgroundColor: '',
  },
  {
    id: 2,
    size: 'IMG500_500',
    title: '',
    titleSize: 12,
    titleColor: '',
    titleBold: false,
    titleItalic: false,
    titleUnderline: false,
    titleFamily: '',
    mainImage: '',
    backgroundImage: '',
    backgroundColor: '',
    buttonTitle: '',
    buttonColor: '',
    buttonBackgroundColor: '',
  },
]