export const navigationName = {
  "/board/dashboard": "홈/대시보드",
  "/board/myPageUser": "홈/마이페이지",
  "/board/myPageAdmin": "홈/마이페이지",
  "/board/campaign": "홈/광고 관리/캠페인생성",
  "/board/createCreative": "홈/광고 관리/크리에이티브 생성",
  "/board/manageCreative": "홈/광고 관리/크리에이티브 관리",
  "/board/reports": "홈/보고서/보고서 생성",
  "/board/reportsDaily": "홈/보고서/일별 보고서",
  "/board/reportsCPC": "홈/보고서/CPC 보고서",
  "/board/platform": "홈/플랫폼 관리/사용자 관리",
  "/board/platformDetail": "홈/플랫폼 관리/사용자 관리",
  "/board/categoryManage": "홈/플랫폼 관리/광고주 카테고리 관리",
  "/board/productManage": "홈/플랫폼 관리/상품 수집 관리",
  "/board/changeManage": "홈/플랫폼 관리/전환 관리",
  "/board/paymentManage": "홈/플랫폼 관리/결재 관리",
  "/board/settings": "홈/설정/이벤트 단가 관리",
  "/board/settingsDetail": "홈/설정/이벤트 단가 상세 관리",
  "/board/budgetEvent": "홈/설정/이벤트 예산 관리",
  "/board/budgetEventDetail": "홈/설정/이벤트 예산 상세 관리",
  "/board/budgetTime": "홈/설정/시간별 예산 관리",
  "/board/budgetTimeDetail": "홈/설정/시간별 예산 상세 관리",
  "/board/pixel": "홈/픽셀 관리",
  "/board/pixelDetail": "홈/픽셀 관리 상세",
}
export const dataTotalInfo = {
  totalCount:1,
  totalPages:1,
  currentPage:1
}
